---
- name: Learning Conditions
  hosts: all
  become: true
  tasks:
   - name: Create a user named deep
     user:
      name: deep
      state: present
     when: 
      - ansible_facts.distribution == "Ubuntu" 
      - ansible_facts.bios_version > "2.0.0"

   - name: Create a user named deep2
     user:
      name: Deep
      state: present
     when: ansible_facts.distribution == "CentOS" or ansible_facts.bios_version > "2.0.0"
