---
- name: deploying /tmp/myhosts
  hosts: all
  vars:
   user_list:
    - Deep
    - Deep2
    - Deep3
  become: true
  tasks:
   - name: deploying hosts file now
     template:
      src: hosts.j2
      dest: /tmp/myhosts
     when: inventory_hostname in groups['dev']
